### ISSUE TITLE
Query about the coldstart measure

### ISSUE THREAD

**Issue by hazelnutsgz** [liangw89/faas_measure#1]
Hi, I am an undergraduate researcher from Fudan University in China. I came across the paper on ATC and touch the source code for a while.(Excellent work!) But there are some details I cannot figure out by myself.

Simply put, I am a little confused about the measurement for coldstart latency. Basically, there are 4 timestamps  in the `faas_measure` implementation: 
`before invoke(client side)`
                    ||
`entering lambda function(server side)`
                    ||
`returning from lambda function(server side)`
                    ||
`after invoke(client side)`

So how to figure out the coldstart time out of these metrics? My intuitive solution is `entering lambda function(server side)` - `before invoke(client side)`, based on the assumption that network traffic is trivial.

I am definitely a newbie in the measurement area, but I am interested in digging out each piece of detail. Hope to hear from you~

**Comment by liangw-sec** [comment]
Yes, coldstart = entering lambda function(server side) - before invoke(client side)

**Comment by hazelnutsgz** [comment]
Thanks~

**Comment by hazelnutsgz** [comment]
A very tricky phenomenon occurred on Azure Function when I adapted this measurement. The latency(s) became a **negative** number. I set both the Azure Function(NodeJS environment) and client in the same region(Eastern American). 

I was wondering if there is any explanation for it, thanks~

**Comment by liangw-sec** [comment]
Did you sync the clock as mentioned in Sec 3 of the paper? 

I'd suggest you send me emails for non-code questions.
