### ISSUE TITLE
Network throughput has no change

### ISSUE THREAD

**Issue by YiLingYiLing** [liangw89/faas_measure#2]
I care the network throughput.  I use the executable file iperf3 in a m5.large instance in us-east-1, and I also package the iperf3 file as well as the tests code in a '.zip' file. However, I find no matter how I change the memory size of Lambda function (128MB-3008MB), the throughput is always about 708Mbps. Here are the two logs:
 log of 128MB memory:  
04:01:59
START RequestId: 4b0c7b46-cd00-4184-b2d4-1ed29f80f175 Version: $LATEST
START RequestId: 4b0c7b46-cd00-4184-b2d4-1ed29f80f175 Version: $LATEST
04:02:10
708.066961363,1629,1069,2306
04:02:10
END RequestId: 4b0c7b46-cd00-4184-b2d4-1ed29f80f175
04:02:10
REPORT RequestId: 4b0c7b46-cd00-4184-b2d4-1ed29f80f175 Duration: 10330.64 ms Billed Duration: 10400 ms Memory Size: 128 MB Max Memory Used: 58 MB Init Duration: 163.03 ms

log of 3008MB memory 
04:02:34
START RequestId: 7bf028de-ce20-4a19-ba7e-a8a1cb038d16 Version: $LATEST
04:02:44
706.241694002,1507,1121,3245
04:02:44
END RequestId: 7bf028de-ce20-4a19-ba7e-a8a1cb038d16
04:02:44
REPORT RequestId: 7bf028de-ce20-4a19-ba7e-a8a1cb038d16 Duration: 10190.47 ms Billed Duration: 10200 ms Memory Size: 3008 MB Max Memory Used: 61 MB Init Duration: 155.66 ms

**Comment by liangtingwang** [comment]
Iperf could be CPU-bound in this case. Please try to increase the coresident level (as in sec 6.2)

**Comment by YiLingYiLing** [comment]
Yes, I only test one Lambda function. Thank you very much.
