### ISSUE TITLE
identify the function co-locate for AWS Lambda functions

### ISSUE THREAD

**Issue by YiLingYiLing** [liangw89/faas_measure#3]
Hello, I try to print the instance private ip and the vm private ip using the function inst_priv_ip() and vm_priv_ip() in stats.py for my own Lambda function with DNN training workload. And I set up a Lambda function and invoke 10 concurrent Lambda functions at 1024MB. All the concurrent  functions have the same instance  private ip but the different  vm private ip ( 169.254.76.1).  Then I try to get the "instance root ID" from "/proc/self/cgroup" file. And all the concurrent  functions have different "vm_id"(sandbox-root-xxxxxx) and "inst_id"(sandbox-xxxxxx). Do that means all these 10 concurrent Lambda functions are not in the same VM host? Is it only reliable to use this method to identify the function co-located using I/O-based coresidency test in AWS(figure3 in paper)？

**Comment by liangtingwang** [comment]
It's better to double check whether our method is still working. It's easy for AWS to obfuscate or remove the VM identity information to make co-location detection harder. I/O-based coresidency test should be more reliable than cgroup information.

**Comment by YiLingYiLing** [comment]
Thank you very much!
