### ISSUE TITLE
How to Set-Up

### ISSUE THREAD

**Issue by lisakp96** [liangw89/faas_measure#4]
Hi ! I am a Masters student in Edinburgh, and would like to use your framework on my Lambda function to measure latency and cold start. However I am new to this and couldn't manage to set it up, so I am kindly asking if you got a second of describe how to integrate this to measure, let's say, a simple Lambda & API Gateway that just returns a Hello World ? All the Best, Lisa

**Comment by liangw-sec** [comment]
Hi, 

You only need to modify conf.py to add your credentials and roles then you should be able to run most of the *_test.py scripts. The scripts will automatically create and invoke functions. For network performance test you need to set up iperf servers in AWS and please check the comments in perf_test.py L34 --- L37 for constructing the events. 

The framework only supports direct function invocation.  You need to do some hacks on your own to route the requests through API gateway.

Thanks,

Laing

**Comment by lisakp96** [comment]
It works smoothly, thank you so much this is just excellent work !
